buildImage = "ghcr.io/railwayapp/nixpacks:ubuntu-1737417843"

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["bun"]
aptPkgs = ["curl", "wget"]

[phases.install]
dependsOn = ["setup"]
cmds = ["bun install]

[phases.build]
dependsOn = ["install"]
cmds = ["cd server && bun run build"]

[start]
cmd = "cd server && bun run src/index.ts"