buildImage = "ghcr.io/railwayapp/nixpacks:ubuntu-1737417843"

[phases.setup]
nixPkgs = ["bun"]
aptPkgs = ["curl", "wget"]

[phases.install]
dependsOn = ["setup"]
cmds = ["bun install"]

[phases.build]
dependsOn = ["install"]
cmds = ["bun run build"]

[start]
cmd = "bun run src/index.ts"